git:
  depth: 1

language: python

python:
  - 3.3
  - 3.4

notifications:
  irc:
    channels:
      - irc.freenode.net##gustavi
    skip_join: true

cache:
  - apt

install:
  - sudo apt-get update
  - sudo apt-get install unzip
  - travis_retry pip install -r requirements.txt

script:
  - cd teamnewheaven
  - coverage run --source='.' manage.py test
  - flake8 --exclude=migrations,urls.py,settings.py teamnewheaven

after_success:
  - coveralls
